name: Build and test

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: adopt:11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: sbt test
        # This runs the template with the default parameters, and runs test within the templated app.
        run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
